repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.13"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        exclude: "_templates"
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.17.1
    hooks:
      - id: slotscheck
        exclude: "test_*|docs|migrations|scripts"
        entry: env PYTHONPATH=src/ slotscheck
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            aiosql,
            uvloop,
            jinja2,
            hiredis,
            passlib,
            rich,
            click,
            rich-click,
            polyfactory,
            structlog,
            aiosmtplib,
            asyncpg,
            asyncpg-stubs,
            httpx,
            pytest,
            saq,
            litestar,
            types-freezegun,
            types-python-jose,
            types-click,
            types-redis,
            types-passlib,
            types-click,
            types-PyYAML,
            uvicorn,
            socketify,
          ]
