repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.291"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        exclude: "_templates"
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.3.0
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools|scripts"
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.17.0
    hooks:
      - id: slotscheck
        exclude: "test_*|docs|migrations|scripts"
        entry: env PYTHONPATH=src/server slotscheck
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            aiosql,
            uvloop,
            jinja2,
            hiredis,
            passlib,
            rich,
            click,
            rich-click,
            polyfactory,
            structlog,
            aiosmtplib,
            asyncpg,
            asyncpg-stubs,
            httpx,
            pytest,
            saq,
            litestar,
            types-freezegun,
            types-python-jose,
            types-click,
            types-redis,
            types-passlib,
            types-click,
            types-PyYAML,
            uvicorn,
            socketify,
          ]
